title: Garden Assistant Application
description: Team Red — CS 410
theme: jekyll-theme-cayman

header_pages:
  - index.md
  - problem.md
  - solution.md
  - deliverables.md
  - presentations.md
  - team.md
 
